FROM oven/bun:1-alpine

WORKDIR /app

COPY apps/web/package.json apps/web/package-lock.json* ./
RUN bun install --frozen-lockfile

COPY apps/web .
COPY packages ./packages

EXPOSE 3000

CMD ["bun", "--watch", "vite"]