FROM oven/bun:1-alpine

WORKDIR /app

COPY apps/api/package.json apps/api/package-lock.json* ./
RUN bun install --frozen-lockfile

COPY apps/api .
COPY packages ./packages

EXPOSE 3001

CMD ["bun", "--watch", "src/index.ts"]